version: "3"
services:
  gen-proto:
    build: .
    volumes:
      - ./proto:/proto
    command:
      - /bin/bash
      - -c
      - |
        protoc --go_out=/proto/gen --go_opt=paths=source_relative \
          --go-grpc_out=/proto/gen --go-grpc_opt=paths=source_relative \
          --grpc-gateway_out /proto/gen \
          --grpc-gateway_opt paths=source_relative \
          --grpc-gateway_opt generate_unbound_methods=true \
          -I /proto /proto/service/**/**/*.proto